title: "The Typewriter Ethic"
description: "A blog about whatever pops into my head at any given time."
author: "The Typewriter Ethic"
email: "typewriterethic@protonmail.com"
url: "https://typewriterethic.com"
baseurl: ""

# Build
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

kramdown:
  input: GFM
  hard_wrap: false

# Pagination
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

paginate: 10
paginate_path: "/side/:num/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      og_image: "/assets/og/og-default.png"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
